# Generated by Django 4.2 on 2023-04-26 06:51

from django.db import migrations, models
import drfecom.product.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(
                null=True, upload_to=drfecom.product.models.product_image_path
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                null=True, upload_to=drfecom.product.models.product_image_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to=drfecom.product.models.product_image_path
            ),
        ),
    ]
